# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-04-09 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
